#   UNC Charlotte 49ers EV Lap Sim program
#   Created by : Matt Verolme
#   Last updated : 8/11/2026

#   Description :
#
#   Reads a track file generated by TrackMapGenerator.py using GPS coordinates.
#
#   Opens up GUI that allows several key car parameters to be edited.
#
#   Pressing 'Calculate' in the interface displays the projected lap time for the track provided
#   as well as projected Skid pad and Acceleration event times.

#---------- Import Statements ----------

import tkinter as tk
from tkinter import ttk, filedialog
import numpy as np

import math
from math import pi

#---------- Initialize Parameters ----------

weight = 580                # Car weight, lbs
track_width = 49.5          # Trackwidth, inches
c_lift = 0.264              # Coefficient of lift
c_drag = 0.585              # Coefficient of drag
frontal_area = 7.9          # Frontal area, ft^2
torque = 112                # Motor torque, N * m
gear_ratio = 3.45           # Gear ratio
wheel_radius = 9            # Wheel radius, in

g = 32.17405                # Gravity, ft/s^2
rho = 0.002282              # Air Density, slug/ft^3
in_to_ft = 1/12             # Inch to feet conversion
nm_to_ftlb = 0.73756        # Newton-meter to Foot-lb conversion

skidpad_radius = 30         # Skidpad Radius, ft
skidpad_angle = 360         # Skidpad turn angle, degrees
accel_distance = 246.06     # Acceleration distance, ft

straight_threshold = 100    # Threshold radius to determine a straight, ft


#---------- Creating file selection interface ----------

class FilePicker(tk.Tk):
    def __init__(self, master):
        self.master = master
        self.master.title("Lap Sim Picker ")
        self.master.geometry("600x150")
        self.master.configure(bg='#005035')

        self.file_track = tk.StringVar()
        self.create_widgets()


    def create_widgets(self):
        ttk.Button(self.master, text="Track File", command=self.track_file).place(relx = 0.5, rely = 0.25, anchor="center")
        ttk.Label(self.master, textvariable=self.file_track, font=('Calibri 12')).place(relx = 0.5, rely = 0.5, anchor="center")

        ttk.Button(self.master, text="Confirm File Choice", command=self.set_choices).place(relx = 0.5, rely = 0.75, anchor="center")

    def track_file(self):
        self.file_track.set(filedialog.askopenfilename())

    def set_choices(self):
        self.track_path = self.file_track.get()     # Saves track file path as a string

        self.master.destroy()


#---------- Parse Track File ----------

def read_track(text):
    track = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.replace(',', '\t').split('\t')
        track.append([float(parts[0]), float(parts[1]), float(parts[2])])

    return track

#---------- Functions ----------

def quadratic_formula(a, b, c):
    root = np.sqrt(b**2 - 4*a*c)
    return [(-b + root)/(2*a), (-b - root)/(2*a)]

def quadratic_function(coefficient, x):
    return coefficient[0] * (x**2) + coefficient[1] * x + coefficient[2]

def seconds_to_ms(seconds):
    minutes = int(seconds // 60)
    seconds = seconds % 60
    return f'{minutes}:{seconds:.3f}'

#---------- Car Class ----------

class Car:
    def __init__(self, w, cl, cd, fa, tw, wr, tq, gr):
        self.weight = w
        self.mass = w / g
        self.c_lift = -1 * cl # Change from standard sign convention
        self.c_drag = cd
        self.frontal_area = fa
        self.tw = (tw + 6) * in_to_ft
        self.wheel_radius = wr * in_to_ft
        self.torque = tq * nm_to_ftlb
        self.gear_ratio = gr

        # Tire coefficients/parameters for Hoosier 16x6-7 at 12 psi:

        self.pdy1 = 2.65159         # Lateral friction Muy at nominal load (Fz0)
        self.pdy2 = -0.115147       # Variation of friction Muy with load
        self.fz0 = 146.126          # Nominal tire load, lbf
        self.scaling_factor = 0.6   # Muy scaling factor

        self.dt = 0.01              # Integration time step, s


    # Downforce in lbf based on velocity
    def downforce(self, v):
        return 0.5 * self.c_lift * rho * self.frontal_area * v**2

    # Drag in lbf based on velocity
    def drag(self, v):
        return abs(0.5 * self.c_drag * rho * self.frontal_area * v ** 2)

    # Load dependant lateral friction coefficient
    def mu_y(self, fz_tire):
        dfz = (fz_tire - self.fz0) / self.fz0
        return (self.pdy1 + self.pdy2 * dfz) * self.scaling_factor

    # Finds maximum theoretical cornering velocity based on available grip and corner radius
    def cornering_speed(self, r):
        r = r + self.tw / 2     # Assumes width of track = car trackwidth
        v = 35                  # Initial velocity guess, ft/s
        for _ in range(1000000):
            fz_tire = (self.weight + self.downforce(v)) / 4     # Total Fz per tire, including downforce
            mu = self.mu_y(fz_tire)                             # Load dependent Mu_y

        # Creates quadratic equation to find the velocity at which lateral force required = lateral force available
        # Based on: (m * V^2) / r = Mu * (m * g + (0.5 * C_l * Rho * FA * V^2))
        # Which can be rearranged to the following quadratic equation:
        # ((m/r)-(0.5 * C_l * Rho * FA))V^2  -  (Mu * m * g)  =  0
            a = (self.mass / r) - mu * (0.5 * abs(self.c_lift) * rho * self.frontal_area)
            c = -mu * self.weight
            v_new = max(quadratic_formula(a, 0, c))

        # Function will iterate until v and v_new converge
            if abs(v_new - v) < 0.0001:
                return v_new
            v = v_new

        return v

    # Determines cornering based on radius and total turn angle
    # Currently only used for calculating skidpad time
    def cornering_time(self, r, theta):
        v = self.cornering_speed(r)
        r = r + self.tw/2
        d = 2 * pi * r * ( theta / 360)
        time = d / v
        return time

    # Calculates time to drive entire distance of a straight
    # Currently only used for estimating accel time
    def straight_time(self, v_0, v_f, length):
        t = 0
        d = 0
        v = v_0

        while d < length:
            a = ((self.torque * gear_ratio / self.wheel_radius) - self.drag(v)) / self.mass
            v += a * self.dt
            d += v * self.dt
            t += self.dt

        if v_f == -1:
            return t

        return t

    # Determines velocity limit at each interval across an entire lap
    # This is the main function used for estimating lap times for a given track
    def velocity_profile(self, rows):

        n = len(rows)
        row_spacing = rows[1][1] - rows[0][1]   # Feet covered between each interval in track file
        lap_length = rows[-1][1] + row_spacing  # Estimated lap length, ft

        # Initialize list for cumulative distance and corner radius at each point
        distances = []
        radii = []

        for row in rows:
            distances.append(row[1])
            radii.append(row[2])

        v_max = [] # List of velocity limits at each point

        for r in radii:
            if abs(r) >= straight_threshold:        # This guesses whether a point along the lap is part of a straight or a corner
                v_max.append(float('inf'))          # If a point is deemed to be on a straight, there is no velocity limit
            else:
                vl = self.cornering_speed(abs(r))   # If a point is deemed to be along a corner, its max velocity is calculated
                v_max.append(vl)

        # Duplicates all track points to create a two lap window
        extended_distances = distances
        lap_two = []
        for d in distances:
            lap_two.append(d + lap_length)
        extended_distances += lap_two
        extended_radii = radii * 2
        extended_v_max = v_max * 2

        extended_v = extended_v_max[:]

        # Forward accel pass; determines max velocity at each point based on acceleration and previous velocity
        for i in range(1, 2 * n):

            ds = extended_distances[i] - extended_distances[i - 1]    # Distance covered between each point
            v_prev = extended_v[i - 1]    # Gets velocity at previous point
            r = extended_radii[i]

            fz_tire = (self.weight + self.downforce(v_prev)) / 4    # Total Fz per tire
            mu = self.mu_y(fz_tire)    # Load dependent friction coefficient

            # Determines total friction force available from all tires; this is the radius of the friction circle
            f_total = mu * (self.weight + self.downforce(v_prev))

            # Lateral force required to take corner at previous velocity
            f_lateral = (self.mass * v_prev ** 2) / abs(r)

            # Remaining friction force available for longitudinal force
            f_long_max = math.sqrt(max(0, (f_total ** 2) - (f_lateral ** 2))) # 'max' function guards against negative number in sqrt

            # Finds force limit of powertrain and traction. Smaller value is actual driving force limit
            f_drive = min((self.torque * self.gear_ratio / self.wheel_radius), f_long_max)

            # Finds acceleration limit, accounting for drag
            a = (f_drive - self.drag(v_prev)) / self.mass

            # Finds new velocity using V^2 = V_0^2 + 2ax
            v_new = math.sqrt((v_prev ** 2) + 2 * a * ds)

            # Compares v_new to pure cornering velocity limit and keeps lesser value
            extended_v[i] = min(extended_v_max[i], v_new)

        extended_v_accel = extended_v[n:]   # Discards first lap of data, keeps only second

        extended_v_decel = extended_v_max[:]
        
        # Backwards decel pass; determines max velocity at each point based on decel and max velocity at point after
        for i in range(2 * n - 2, -1, -1):
 
            ds = extended_distances[i + 1] - extended_distances[i]    # Distance covered between each point
            v_next = extended_v_decel[i + 1]    # Gets velocity at following point
            r = extended_radii[i]
            
            fz_tire = (self.weight + self.downforce(v_next)) / 4    
            mu = self.mu_y(fz_tire)    
            f_total = mu * (self.weight + self.downforce(v_next))
            
            f_lateral = self.mass * v_next ** 2 / r

            # Maximum braking force based on friction force available
            f_brake_max = math.sqrt(max(0.0, f_total ** 2 - f_lateral ** 2))

            # Deceleration from braking and drag
            a_decel = (self.drag(v_next) + f_brake_max) / self.mass

            # Finds new velocity using V^2 = V_0^2 + 2ax
            v_new = math.sqrt(v_next ** 2 + 2 * a_decel * ds)

            # Compares velocity determined by braking to pure cornering limit, keeps lesser value
            extended_v_decel[i] = min(extended_v_decel[i], v_new)

        # Discards second lap of data
        v_decel = extended_v_decel[:n]

        # Returns lowest velocity from cornering, accel, and decel calculations
        return [min(v_max[i], extended_v_accel[i], v_decel[i]) for i in range(n)]

    def lap_time(self, rows):

        t = 0.0    # Starting time
        n = len(rows)
        v_actual = self.velocity_profile(rows)    # Gets velocity at each point

        distances = []    # List of cumulative distance at each point
        for row in rows:
            distances.append(row[1])

        row_spacing = distances[1] - distances[0]    # Distance step between rows
        lap_length = distances[-1] + row_spacing     # Total lap length
        distances_loop = distances + [lap_length]    # Adds distance of interval connecting last point to first point to close the loop
        
        # Adds velocity connecting last point to first. Sets velocity at end of lap to velocity at start of lap
        v_loop = v_actual + [v_actual[0]]     
        
        for i in range(1, n + 1):
            
            ds = distances_loop[i] - distances_loop[i - 1]    # Distance covered between two points
            v_avg = (v_loop[i] + v_loop[i - 1]) / 2           # Average velocity over interval between consecutive points
            t += ds / v_avg                                   # Cumulative lap time over each segment

        lap_count = 72178.5 / lap_length    # Estimates number of laps needed to complete full endurance distance (22km)
        total_time = t * lap_count          # Scales single lap time over entire endurance distance

        return t, total_time


#---------- GUI Setup ----------

class LapSimApp(tk.Tk):

    # Initializing class
    def __init__(self, master, track):
        
        self.master = master
        self.track = track
        self.master.title("Lap Sim")
        self.master.geometry("800x550")        # GUI window size (width x height)
        self.master.configure(bg='#005035')    # GUI background color (Charlotte Green)

        self.param_vals = {}    # Dictionary containing paramater names and their values
        self.event_times = {}   # Dictionary containing event names and times
        
        self.ui_style()
        self.widgets_layout()

    # Defining appearence of each widget type
    def ui_style(self):
        
        style = ttk.Style(self.master)
        style.theme_use("classic")
        style.configure('TFrame', background='#005035')
        style.configure('TLabel', background='#005035', foreground='#FFFFFF', font=('Helvetica', 16))
        style.configure('Header.TLabel', background='#005035', foreground='#F1E6B2', font=('Helvetica', 22, ' bold'))
        style.configure('Result.TLabel', background='#005035', foreground='#10EFE5', font=('Helvetica', 22, ' bold'))
        style.configure('TButton', background='#F1E6B2', foreground='#005035', font=('Helvetica', 12, ' bold'))
        style.configure('TEntry', background='#FFFFFF', font=('Helvetica', 14))

    # Creating widgets
    def widgets_layout(self):

#---------- Parameter Frame ----------

        params_frame = ttk.Frame(self.master, style='TFrame')
        params_frame.place(relx=0.05, rely=0.05, relwidth=0.45, relheight=0.9, anchor= 'nw')

        entry_space_right = 150

        ttk.Label(params_frame, text="Car Parameters:", style='Header.TLabel').grid(row=0, column=0, columnspan=2, sticky='w')

        ttk.Label(params_frame, text='Weight (lbs)', style='TLabel').grid(row=1, column=0, sticky='w', padx=5, pady=(25,10))
        self.weight_var = tk.StringVar(value=str(weight))
        ttk.Entry(params_frame, textvariable=self.weight_var, style='TEntry').grid(row=1, column=1, sticky='e', padx=(0,entry_space_right), pady=(25,10))
        self.param_vals['weight'] = self.weight_var

        ttk.Label(params_frame, text='Lift Coefficient', style='TLabel').grid(row=2, column=0, sticky='w', padx=5, pady=10)
        self.cl_var = tk.StringVar(value=str(c_lift))
        ttk.Entry(params_frame, textvariable=self.cl_var, style='TEntry').grid(row=2, column=1, sticky='e', padx=(0,entry_space_right), pady=10)
        self.param_vals['c_lift'] = self.cl_var

        ttk.Label(params_frame, text='Drag Coefficient', style='TLabel').grid(row=3, column=0, sticky='w', padx=5, pady=10)
        self.cd_var = tk.StringVar(value=str(c_drag))
        ttk.Entry(params_frame, textvariable=self.cd_var, style='TEntry').grid(row=3, column=1, sticky='e', padx=(0,entry_space_right), pady=10)
        self.param_vals['c_drag'] = self.cd_var

        ttk.Label(params_frame, text='Frontal Area (ft^2)', style='TLabel').grid(row=4, column=0, sticky='w', padx=5, pady=10)
        self.fa_var = tk.StringVar(value=str(frontal_area))
        ttk.Entry(params_frame, textvariable=self.fa_var, style='TEntry').grid(row=4, column=1, sticky='e', padx=(0,entry_space_right), pady=10)
        self.param_vals['frontal_area'] = self.fa_var
        
        ttk.Label(params_frame, text='Track Width (in)', style='TLabel').grid(row=6, column=0, sticky='w', padx=5, pady=10)
        self.tw_var = tk.StringVar(value=str(track_width))
        ttk.Entry(params_frame, textvariable=self.tw_var, style='TEntry').grid(row=6, column=1, sticky='e', padx=(0,entry_space_right), pady=10)
        self.param_vals['track_width'] = self.tw_var
        
        ttk.Label(params_frame, text='Wheel Radius (in)', style='TLabel').grid(row=7, column=0, sticky='w', padx=5, pady=10)
        self.rwheel_var = tk.StringVar(value=str(wheel_radius))
        ttk.Entry(params_frame, textvariable=self.rwheel_var, style='TEntry').grid(row=7, column=1, sticky='e', padx=(0,entry_space_right), pady=10)
        self.param_vals['wheel_radius'] = self.rwheel_var
        
        ttk.Label(params_frame, text='Torque (Nm)', style='TLabel').grid(row=8, column=0, sticky='w', padx=5, pady=10)
        self.torque_var = tk.StringVar(value=str(torque))
        ttk.Entry(params_frame, textvariable=self.torque_var, style='TEntry').grid(row=8, column=1, sticky='e', padx=(0,entry_space_right), pady=10)
        self.param_vals['torque'] = self.torque_var
        
        ttk.Label(params_frame, text='Gear Ratio', style='TLabel').grid(row=9, column=0, sticky='w', padx=5, pady=10)
        self.gr_var = tk.StringVar(value=str(gear_ratio))
        ttk.Entry(params_frame, textvariable=self.gr_var, style='TEntry').grid(row=9, column=1, sticky='e', padx=(0,entry_space_right), pady=10)
        self.param_vals['gear_ratio'] = self.gr_var

        ttk.Button(params_frame, text='Compute', style='TButton', command=self.compute).grid(row=10, column=0, sticky='e', columnspan=2, padx=(0,250), pady=10)


#---------- Result Frame ----------


        results_frame = ttk.Frame(self.master, style='TFrame')
        results_frame.place(relx=0.55, rely=0.05, relwidth=0.4, relheight=0.9, anchor= 'nw')

        ttk.Label(results_frame, text='Event Times:', style='Header.TLabel').grid(row=0, column=0, columnspan=2, sticky='w')

        ttk.Label(results_frame, text='Endurance (1 Lap):', style='TLabel').grid(row=1, column=0, sticky='w', padx=5, pady=10)
        self.endurance_lap_time = tk.StringVar(value=str('--'))
        ttk.Label(results_frame, textvariable=self.endurance_lap_time, style='Result.TLabel').grid(row=1, column=1, sticky='e', pady=10)
        self.event_times['endurance_lap'] = self.endurance_lap_time

        ttk.Label(results_frame, text='Total Endurance:', style='TLabel').grid(row=2, column=0, sticky='w')
        self.total_endurance_time = tk.StringVar(value=str('--'))
        ttk.Label(results_frame, textvariable=self.total_endurance_time, style='Result.TLabel').grid(row=2, column=1, sticky='e')
        self.event_times['endurance_total'] = self.total_endurance_time

        ttk.Label(results_frame, text='Skidpad:', style='TLabel').grid(row=3, column=0, sticky='w', padx=5, pady=10)
        self.skidpad_time = tk.StringVar(value=str('--'))
        ttk.Label(results_frame, textvariable=self.skidpad_time, style='Result.TLabel').grid(row=3, column=1, sticky='e', pady=10)
        self.event_times['skidpad'] = self.skidpad_time

        ttk.Label(results_frame, text='Accel:', style='TLabel').grid(row=4, column=0, sticky='w', padx=5, pady=10)
        self.accel_time = tk.StringVar(value=str('--'))
        ttk.Label(results_frame, textvariable=self.accel_time, style='Result.TLabel').grid(row=4, column=1, sticky='e',pady=10)
        self.event_times['accel'] = self.accel_time


    def update_params(self):

        # Dictionary containing key : Parameter Name
        params = {'weight' : 'Weight',
                  'c_lift' : 'Lift Coefficient',
                  'c_drag' : 'Drag Coefficient',
                  'frontal_area' : 'Frontal Area',
                  'mu_s' : 'Friction Coefficient',
                  'track_width' : 'Track Width',
                  'wheel_radius' : 'Wheel Radius',
                  'torque' : 'Torque',
                  'gear_ratio' : 'Gear Ratio'
                  }

        values = {}

        # Iterates through each parameter value from the entry boxes 
        for key, var in self.param_vals.items():

            # Reads current value of entry widget
            entry = var.get()

            # Tries to convert entry value from StringVar to a float
            try:
                values[key] = float(entry)

            # If an entry does not contain a number, an error message is given
            except ValueError:
                raise ValueError(f'{params[key]} must be a number. Got {entry}')

        return values    # Returns updated parameter values

    # Connected to compute button in GUI. Updates results with new parameters when called
    def compute(self):

        # Creates dictionary containing parameter names and updated values
        up = self.update_params()

        # Builds new car object using updated parameter values
        car = Car( up['weight'], up['c_lift'], up['c_drag'], up['frontal_area'], up['track_width'], up['wheel_radius'], up['torque'], up['gear_ratio'])

        # Calculate event times using new parameters
        endurance_lap, endurance_total = car.lap_time(self.track)
        skidpad = car.cornering_time(skidpad_radius, skidpad_angle)
        accel = car.straight_time(0, -1, accel_distance)

        # Changes text value of result widgets to display updated times
        self.event_times['endurance_lap'].set(f'{endurance_lap:.3f} s')
        self.event_times['endurance_total'].set(seconds_to_ms(endurance_total))
        self.event_times['skidpad'].set(f'{skidpad:.3f} s')
        self.event_times['accel'].set(f'{accel:.3f} s')

if __name__ == "__main__":
        picker_root = tk.Tk()
        picker = FilePicker(picker_root)
        picker_root.mainloop()

        data_path = picker.track_path
        test_track = read_track(open(data_path).read())

        app_root = tk.Tk()
        app = LapSimApp(app_root, test_track)
        app_root.mainloop()
















